import Foundation
import Testing
@testable import TestContainers

@Test func containerRequest_parallelSafety_defaultsToAutoGeneratedNames() {
    let request = ContainerRequest(image: "redis:7")

    #expect(request.autoGenerateName == true)

    let resolvedName = request.resolvedName()
    #expect(resolvedName != nil)
    #expect(resolvedName?.hasPrefix("tc-swift-") == true)
}

@Test func containerRequest_parallelSafety_withName_defaultsToFixedName() {
    let request = ContainerRequest(image: "redis:7")
        .withName("redis-fixed")

    #expect(request.name == "redis-fixed")
    #expect(request.autoGenerateName == false)
    #expect(request.resolvedName() == "redis-fixed")
}

@Test func containerRequest_parallelSafety_withAutoGeneratedName_usesProvidedPrefix() {
    let request = ContainerRequest(image: "redis:7")
        .withAutoGeneratedName("redis-suite")

    #expect(request.name == "redis-suite")
    #expect(request.autoGenerateName == true)
    #expect(request.resolvedName()?.hasPrefix("redis-suite-") == true)
}

@Test func containerRequest_parallelSafety_withFixedName_disablesAutoGeneration() {
    let request = ContainerRequest(image: "redis:7")
        .withFixedName("redis-debug")

    #expect(request.autoGenerateName == false)
    #expect(request.resolvedName() == "redis-debug")
}

@Test func containerRequest_parallelSafety_resolvedName_generatesDifferentValuesPerCallWhenAutoGenerated() {
    let request = ContainerRequest(image: "redis:7")

    let name1 = request.resolvedName()
    let name2 = request.resolvedName()

    #expect(name1 != nil)
    #expect(name2 != nil)
    #expect(name1 != name2)
}

@Test func containerRequest_parallelSafety_withName_autoGenerateTrue_generatesUniqueNames() {
    let request = ContainerRequest(image: "redis:7")
        .withName("redis-shared", autoGenerate: true)

    let name1 = request.resolvedName()
    let name2 = request.resolvedName()

    #expect(name1?.hasPrefix("redis-shared-") == true)
    #expect(name2?.hasPrefix("redis-shared-") == true)
    #expect(name1 != name2)
}

@Test func containerRequest_parallelSafety_withRandomPort_addsRandomPortMapping() {
    let request = ContainerRequest(image: "redis:7")
        .withRandomPort(6379)

    #expect(request.ports == [ContainerPort(containerPort: 6379, hostPort: nil)])
}

@Test func containerRequest_parallelSafety_withTestLabels_setsSessionTestAndTimestamp() {
    let request = ContainerRequest(image: "redis:7")
        .withLabel("existing", "value")
        .withTestLabels(testName: "parallel-suite", sessionID: "session-123")

    #expect(request.labels["existing"] == "value")
    #expect(request.labels["testcontainers.swift.test"] == "parallel-suite")
    #expect(request.labels["testcontainers.swift.session"] == "session-123")
    #expect(request.labels["testcontainers.swift.timestamp"] != nil)
}

@Test func containerRequest_parallelSafety_withParallelSafetyStrict_setsSessionLabel() {
    let request = ContainerRequest(image: "redis:7")
        .withParallelSafety(.strict)

    #expect(request.autoGenerateName == true)
    #expect(request.labels["testcontainers.swift.session"] != nil)
}

@Test func containerRequest_parallelSafety_withParallelSafetyCustom_appliesConfig() {
    let config = ParallelSafetyConfig(
        autoGenerateNames: false,
        sessionID: "custom-session",
        validatePortAllocation: false
    )

    let request = ContainerRequest(image: "redis:7")
        .withParallelSafety(config)

    #expect(request.autoGenerateName == false)
    #expect(request.labels["testcontainers.swift.session"] == "custom-session")
}
