name: 1 - Workflow complete Swift Vapor CI/Security review

# El flujo se activa al hacer push o abrir un PR en la rama principal
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos-26-build-and-test:
    runs-on: macos-26
    steps:
      - name: Version of swift
        run: swift --version

#      - name: Dump github context
#        run: |
#	  echo ${{ github }}
#             echo ${{ github.actor }}

      # 2. Info about container
      - name: Brew info about container
        run: |
              echo $SHELL
              brew install container
              echo "Primer paso"
              brew info container

              #echo "Segundo paso"
              #ls /opt/homebrew/Cellar/container/0.11.0/libexec/container-plugins/ps

              echo "Tercer paso"
              which container

              echo "Cuarto paso"
              #container system start
              printf 'Y\n' | container system start

              echo "Quinto paso"
              container system status

              echo "Último paso"
              launchctl list | grep container

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Use of cache
        uses: actions/cache@v5
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Compila el proyecto
        run: swift build

      - name: Run VaporWithTestsInAppleContainers
        run: |
              TESTCONTAINERS_RUN_APPLE_CONTAINER_TESTS=1 swift test --filter VaporWithTestsINAppleContainers
              swift test --filter VaporWithTestsInAppleContainers 2>&1 | tee tests_output.txt
              if grep -q "suites failed" tests_output.txt; then
                echo "Fallaron los tests"
                exit 1
              fi
              if grep -q "error: fatalError" tests_output.txt; then
                echo "Error fatal grave"
                exit 1
              fi
              echo "Todos los tests del target VaporWithTestsInAppleContainer pasaron satisfactoriamente"

      - name: Info sobre las imágenes, contenedores de Apple Container
        run: |
              echo "Paso container system"
              container system status

  build-and-test:
    needs: macos-26-build-and-test
    # Vapor suele ejecutarse en entornos Linux para servidor
    runs-on: ubuntu-latest
    steps:
#      - name: Dump github context
#        run: |
#	  echo ${{ github }}
#             echo ${{ github.actor }}

      # Info about Docker Engine, api version
      - name: Verificar version docker engine, api
        run: |
         ls -la $(which docker)
         #docker ps
         docker version
         docker context show
         docker context ls
         #docker context inspect
      
      # Descarga el código del repositorio en el ejecutor
      #- name: Checkout code
      #  uses: actions/checkout@v6

      # 4. Instala la herramienta Swiftly y la última versión de Swift TODO
      # Swiftly pone el ejecutable de 'swift' en el PATH del ejecutor
      - name: Install Swift
        uses: vapor/swiftly-action@v0.2.1
        with:
          toolchain: latest

      # . Descarga el código del repositorio en el ejecutor
      - name: Checkout code
        uses: actions/checkout@v6

      # Cache
      - name: Use of cache
        uses: actions/cache@v5
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      # 6. Compila el proyecto
      - name: Build Project
        run: swift build

      # 7. Lanza los tests enfocándose en el target VaporWithTestContainersTests
      # Nota: El comando 'swift test --filter' es el estándar de Swift Package Manager
      - name: Run VaporWithTestContainersTests
        run: |
             # probando a crear socket intermedio que me loguee todo el tráfico
             echo "sudo apt install socat"
             sudo apt install socat
             echo "which socat"
             which socat
             echo "socat -v ...."
             socat -v UNIX-LISTEN:/tmp/docker-debug.sock,fork UNIX-CONNECT:/var/run/docker.sock 2>/tmp/docker-traffic.log &
             SOCAT_PID=$!
             #echo "swift test..."
             #swift test --filter VaporWithTestContainersTests 2>&1 | tee tests_output.txt
             export TESTCONTAINERS_RUNTIME=docker
             TESTCONTAINERS_RUN_DOCKER_TESTS=1 swift test --filter VaporWithTestContainersTests
             kill $SOCAT_PID
             cat /tmp/docker-traffic.log
             if grep -q "suites failed" tests_output.txt; then
               echo "Fallaron los tests"
               exit 1
             fi
             if grep -q "error: fatalError" tests_output.txt; then
               echo "Error fatal grave"
               exit 1
             fi
             echo "vemos las imagenes que existen en docker"
             docker images
             echo "listado de contenedores"
             docker ps
             echo "borramos las imágenes docker"
             docker image ls --format "{{.ID}}" | xargs -r docker rmi
             #docker image ls --format "{{.IMAGE}}" | xargs -r docker rmi
             echo "Todos los tests pasaron satisfactoriamente"
             # Es otra forma de lanzar los tests, comprobando su resultado satisfactorio o no
  security-review:
    needs: build-and-test          # solo corre si build-and-test pasa
    if: github.event_name == 'pull_request'   # solo en PRs, no en push a main
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      pull-requests: write
      contents: read
      discussions: write
    steps:
      - name: Checkout code
        uses: action/checkout@v6

      - name: Security code review by Anthropic
        uses: anthropics/claude-code-security-review@main
        with:
          comment-pr: true
          claude-api-key: ${{ secrets.CLAUDE_API_KEY }}
          claude-model: claude-haiku-4-5-20251001
          exclude-directories: "Tests/VaporWithTestContainersTests"
          # run-every-commit: true # corre en cada commit, false solo la primera vez
